### ISSUE TITLE
Support for fetching `vars-store.yml` via `get`

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-deployment-resource#10]
Ran into an issue today where we needed access to the `vars-store.yml` after our deployment finished. Didn't look like this resource supported downloading the vars-store as part of `get`, so we attempted to fetch the file with the `gcs-resource` instead. However, we didn't realize that Concourse pins all `get` versions to latest at the start of the build ([context](https://concourseci.slack.com/archives/C07RY25QF/p1495132402007558)).

Could the resource be updated to grab the `vars-store.yml` as part of `get`? For additional trickiness, we're also using the resource's `target_file` to dynamically target our director in the same step.

Thanks!

**Comment by xyloman** [comment]
+1 I need something similar we do not have access to use GCS so if the vars-store could be outputted to the input directory we could then use the vars-store.yml in a follow up task which might be to push it to s3.

**Comment by drich10** [comment]
@xyloman I do like the idea of making the file a possible `output` of doing a deployment. I think it is a simpler way to support what was being asked for above. Would this work for you @ljfranklin?

**Comment by ljfranklin** [comment]
@drich10 it's early so I might be missing something, but I think it's a `get` either way. Concourse follows every `put` with an implicit `get` to make files available to subsequent tasks. I don't think you're allowed to modify the input directory with a `put`, might be mistaken though.

**Comment by drich10** [comment]
@ljfranklin yeah I've been investigating this since I posted my reply above. It does look like this requires additional `get` functionality. I'll look into this more from that angle. @xyloman there doesn't seem to be a _simple_ way to get this working for you without adding another storage provider. 

Follow on question for the two of you (which should have been the first thing I did). What specifically have you wanted the `vars-store.yml` for?

**Comment by ljfranklin** [comment]
@drich10 back when I opened this no one was using CredHub so we needed to fetch the vars-store in order to get our generated creds out of BOSH. Honestly now that CredHub has arrived I don't know how useful fetching the vars-store would be, probably a credhub-resource is a better fit for grabbing creds. I only tend to use vars-store now for `create-env` bootstrapping flows which this resource doesn't support.

**Comment by drich10** [comment]
Makes sense, glad time seems to have invalidated this feature for me. I'm going to close this issue since deploying a Bosh director with Credhub is the future AFAIK. @xyloman feel free to re-open this if for some reason deploying/using a credhub enabled Bosh director does not work for you.
