### ISSUE TITLE
Release and stemcell metadata ignore ops files

### ISSUE THREAD

**Issue by mdelillo** [cloudfoundry/bosh-deployment-resource#14]
When specifying a release that is added to the deployment manifest via an opsfile, we get the following error: `Release <release name> not defined in deployment manifest`. It looks like the release (and stemcell) metadata is consumed from the provided deployment manifest ([here](https://github.com/cloudfoundry/bosh-deployment-resource/blob/df91b8540662c8e6303149dbf8b14e582a1f4ad4/out/out_command.go#L45-L53)). The metadata should be retrieved from the manifest downloaded from the bosh director because it has had the ops files applied. But the releases and stemcells still need to be uploaded before deploying.

This is a common pattern used when deploying [cf-deployment](https://github.com/cloudfoundry/cf-deployment), especially when adding [windows cells](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/windows-cell.yml).

Thanks,
@mdelillo @aminjam

**Comment by goonzoid** [comment]
+1, this is a problem for us as well.
