### ISSUE TITLE
delete a deployment

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/bosh-deployment-resource#18]
It would be great to have `put` be able to delete a deployment.

**Comment by drich10** [comment]
I agree. Seems like a reasonable addition. I'll go ahead and add this to the list of features to implement in the near term. Always happy to accept PRs as well :)

**Comment by jtarchie** [comment]
I'll look into it.

**Comment by drich10** [comment]
Hey there! Closing this issue as this feature was just released as part of [2.8.0](https://github.com/cloudfoundry/bosh-deployment-resource/releases/tag/v2.8.0).
