### ISSUE TITLE
The latest docker image points to a non-existent tag

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry/bosh-deployment-resource#19]
The latest docker image points to git tag `v2.5.1` which does not exist in [the bosh-deployment-resource repo](https://github.com/cloudfoundry/bosh-deployment-resource/blob/v2.5.1/Dockerfile).

/cc @kellygerritz

**Comment by drich10** [comment]
Apologies, this was the result of trying to do a release manually. The pipeline that did this previously did this was in the process of being recreated. I believe I have correctly cleaned up the artifacts to the failed `v2.5.1` release attempt. Please re-open this issue if you find something I missed.
