### ISSUE TITLE
Adding support for export-release

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-deployment-resource#2]
Hi @wendorf & @drich10!

As we all start using cf-deployment more and more, at some point teams will need to start producing pre-compiled releases. Although there are many ways we could do this, having an extra param on this resource that automatically outputs the pre-compiled tarball after a successful deploy would be pretty sweet. WDYT?

**Comment by wendorf** [comment]
I agree that it'd be pretty useful for release authors to be able to get their compiled releases... but this sorta feels like a new `bosh-release-resource` instead of a feature of the deployment resource. I get that the compiled release is technically an artifact of the deploy, but I'm not sure that feature belongs here. I'm very open to debate, though, since it'd be a pretty easy feature to add.

**Comment by ljfranklin** [comment]
@wendorf I just really like the idea that if this feature were added to this resource, you could follow every deployment with a put to a precompiled release s3 bucket. The resource itself would encourage people towards producing and consuming only pre-compiled releases. Unless Rel-Int starts producing pre-compiled releases for every CF team :)

**Comment by wendorf** [comment]
Thinking about this more... Are you asking to have the releases be Concourse-style outputs? As far as I know, this isn't possible from a `put`. Instead, you'd have to configure a blobstore for the releases, the same way you configure `vars_store`. I think it'd make more sense for `get` to support a `compiled_releases` array, where we'd fetch the versions matching the manifest. 

What do you think?

**Comment by ljfranklin** [comment]
@wendorf yep, adding it to the `get` makes sense.

**Comment by wendorf** [comment]
This is now available in [v2.1.0](https://github.com/cloudfoundry/bosh-deployment-resource/releases/tag/v2.1.0). We have enhanced functionality planned (support for deployments with multiple stemcells, support for specifying stemcell version), but this will hopefully be useful to you today.
