### ISSUE TITLE
Rebase while uploading release

### ISSUE THREAD

**Issue by poy** [cloudfoundry/bosh-deployment-resource#20]
If trying to upload a dev release to the director, is there any way to emulate the rebase flag's functionality?

**Comment by drich10** [comment]
If you pass the resource the release tarball via the `releases` configuration the resource will ensure the version in the deployment manifest matches that of the tarball. Does that sufficiently cover the use case for you?

**Comment by poy** [comment]
@drich10 I suppose if I name the release with the sha or something. The problem arises when I don't name it and it collides with a previous dev release.

**Comment by drich10** [comment]
Got it. I'm going to do some investigation and hopefully add the functionality if it is within reason. I will report back shortly!

**Comment by drich10** [comment]
@apoydence had a few conversations with bosh folks. The recommendation I received was to create the release with the `--timestamp-version` flag. This should give you increasing versions across runs of CI. Is that a reasonable solution for you?

**Comment by poy** [comment]
@drich10 Would this occur for only dev releases?

**Comment by cppforlife** [comment]
at the end of the pipeline, once dev passed end to end tests for example, you can use "bosh finalize-release dev.tgz" and commit final metadata. if you dont specify --version on finalize-release it will pick next final version automatically. (https://bosh.io/docs/cli-v2.html#release-creation)

**Comment by poy** [comment]
We will update our pipeline to do this. Closing.
