### ISSUE TITLE
Use of SOCK5 tunnel

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/bosh-deployment-resource#24]
We have the requirement to use a SOCK5 tunnel (which is supported by bosh2 cli).

Can we get the bosh-deployment-resource to add this functionality?   Basically we want to be able to setup the SOCK5 port forwarding and then use the BOSH_ALL_PROXY=socks5://localhost:5000 type of option when the tunnel is setup.

One reason is that bosh-lite ca.crt is hard coded to only accept from 192.168.50.4 but we have a NAT address to this and usually with boshv1 CLI we could connect to the other IP.  But with bosh2 CLI we get a failure since the IP we are using is not correct with regards to the cert defined in bosh lite.   We can get around this through the use of BOSH_ALL_PROXY and setting up a SOCK5 port forward to connect to the bosh director and then use the 192.168.50.4 IP as the address for the env.

We also have some environments where the bosh director is behind a double hop and we in the past used simple ssh port forward and since there was no cert verification we did now have a problem accessing using bosh target localhost:<port> but now we do not want to add "localhost" as a valid IP in the director cert.   Again the socks5 port forwarding will help here.

Any thoughts on how to support this?  We could work on a PR for this but would like some help with how this repo is configured.  We believe this use of SOCK5 port forwarding would be very useful to the community.

**Comment by evanfarrar** [comment]
:+1: to this. BBL is adding jumpboxes to most core dev teams' BOSH directors, and they'll be unable to use this resource at that time. The Infrastructure team will PR a fix for this, when we are able.

**Comment by drich10** [comment]
[2.10.0](https://github.com/cloudfoundry/bosh-deployment-resource/releases/tag/v2.10.0) added configurable usernames for the SOCK5 support PR'd by the infrastructure team. Happy tunneling 🕳 !
