### ISSUE TITLE
405 Method Not Allowed error

### ISSUE THREAD

**Issue by chendrix** [cloudfoundry/bosh-deployment-resource#3]
When using the resource to do a deploy, we encounter the following error.

```
Using environment 'bosh.concourse.ci' as client 'ci'
 100.00% 43.25 KB/s 0s
Could not upload release /tmp/build/put/garden-runc/release.tgz: Uploading release file: Director responded with non-successful status code '405' response '<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
'

```

We verified locally that we can use the new bosh cli with the given client/secret to upload this release.

**Comment by drich10** [comment]
Hi @chendrix,

Thanks for shooting this our way. Is there a chance you could post the director logs with the requests being made so we could compare what is happening in the cli vs the resource? Looking at the cli vs what we're doing I can't see anything painfully obvious here.

**Comment by chendrix** [comment]
Some new information.

Looking at `bosh tasks --recent` actually shows successful tasks for uploading the release that returns the 405.

**Comment by chendrix** [comment]
```
Name      concourse
Version   260.0.0 (00000000)
CPI       google_cpi
Features  compiled_package_cache: disabled
          dns: enabled
          snapshots: disabled
```

**Comment by wendorf** [comment]
Version 2.0.1 fixes this. Thanks for the report!
