### ISSUE TITLE
Cannot delete deployment using example from README as manifest parameter is required

### ISSUE THREAD

**Issue by rmeharg** [cloudfoundry/bosh-deployment-resource#34]
Should this parameter be optional as it is not needed to delete the deployment? 

Or should the README example be updated to include the manifest parameter?

**Comment by drich10** [comment]
Hey there, sorry for the misleading example. In the future I may remove the requirement, but it required more work to make it conditionally optional on the `out` command. I have updated the README to be a better example for now.

**Comment by drich10** [comment]
After some further evaluation and a little more caffeine I went ahead and made the change which is now available in `2.8.1`+. Thanks for raising this!
