### ISSUE TITLE
Supporting YAML as a valid format for `source_file`

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-deployment-resource#4]
The JSON format doesn't support newlines in things like CA certs, requiring scripts to escape those newlines. YAML would avoid this and still keep the existing JSON support.

Also really liking the resource so far!

**Comment by drich10** [comment]
Hi @ljfranklin!

So we originally did "try" to do this but there is an interesting change in behavior that occurs (at least when going from the json package to the  gopkg.in/yaml.v2 package) around merging. When using the built-in json package we get a nifty feature that will deep merge, essentially only overwriting the keys specified in the contents of `source_file`. When using `gopkg.in/yaml.v2` it will wholesale replace the source contents therein requiring the user to specify _ALL_ the configuration. Do you know of a package/solution that would allow us to maintain this behavior?

**Comment by ljfranklin** [comment]
@drich10 no don't know of a library off hand. Since there are only a few fields in `source_file` it wouldn't be hard to manually write a deep merge function, but I understand that it's not as nice implementation-wise as the JSON deep merge.

**Comment by wendorf** [comment]
This is now available in v2.3.0 and on Docker Hub with the `latest` tag. Thanks for the suggestion!
