### ISSUE TITLE
Support for bosh-cli --var-file

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/bosh-deployment-resource#46]
Many resources like bosh-io stemcell and S3 put the version of the resource in a file.  It would be great if in my bosh manifest I could parameterize the version of stemcell or a release and supply that value from their respective resource version files.

It seems that today I'd need to create a task that places those versions into a yml vars-file before invoking the bosh resource.

Bosh cli already supports --var-file.  Would be great if --var-file was supported in the bosh-deployment-resource as well.

**Comment by drich10** [comment]
I will add this to my list of things to do in the near future. Thanks for bringing the resource interplay to my attention!

**Comment by henderjm** [comment]
Hi @drich10 

Is there any progress on this being available in the latest docker image? It caught us by surprise that it actually isn't available but is documented on master.

EDIT
We tried to use the latest Release Candidate on docker but we got the following error with this configuration:

```yaml
      var_files:
        addons-spec: git-kubo-ci/specs/guestbook.yml
```

```
Reading variable from file '/root/git-kubo-ci/specs/guestbook.yml': Opening file /root/git-kubo-ci/specs/guestbook.yml: open /root/git-kubo-ci/specs/guestbook.yml: no such file or directory
```


/cc @karampok

**Comment by drich10** [comment]
Sorry about the docs and inflight feature being on master. There were some file system lookup issues with the way this was implemented and I haven't had a chance to fix it up yet. I reverted the in-flight changes to reduce the confusion about whether or not this feature exists. I hope to get back to this _soon_. Hopefully sometime in the next week or so?

**Comment by henderjm** [comment]
Hey,

No worries at all @drich10. I was actually able to get it working in the end. In the Bosh CLI code it looks for an absolute path to the `var_files` argument.
https://github.com/cloudfoundry/bosh-deployment-resource/blob/master/vendor/github.com/cloudfoundry/bosh-cli/director/template/var_file_arg.go#L30

So in order for this to work I just set my value to

```yaml
var_files:
  addons-spec: /tmp/build/put/git-kubo-ci/specs/guestbook.yml
```

Perhaps concourse provides the current working directory which could be prepended on your side to my relative path, resulting in an absolute path Bosh doesn't need to modify.

I'm currently using the latest RC on docker.

**Comment by drich10** [comment]
Should be supported with current directory taken into account as part of the [2.12.0 release](https://github.com/cloudfoundry/bosh-deployment-resource/releases/tag/v2.12.0). Thanks for the nudge and the patience!
