### ISSUE TITLE
Existing Stemcells don't get uploaded to new CPIs added to a director

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/bosh-deployment-resource#47]
Sometimes a stemcell may be uploaded to a director but not to all of the CPI AZs of that director.  It would be nice if it were possible to force and upload of the stemcell so that the director will make sure it is on all of the CPIs.

**Comment by drich10** [comment]
I'm not sure I fully understand the issue here. When does this issue occur? Is this only in a multi-cpi setup? How have you resolved this situation in the past?

**Comment by youngm** [comment]
@drich10 I'm sorry my issue wasn't more clear.  Here are steps to reproduce the issue hopefully this will help.

1. Execute deployment that uploads a stemcell using bosh-deployment-resource
2. Update director cpi config with a new CPI to the director.
3. Execute a deployment that attempts to use the new CPI you will get an error stating the stemcell doesn't exist on that cpi.

To manually fix this situation I can run `bosh upload-stemcell` again and bosh will detect which cpis the stemcell doesn't exist in and it will upload it into those.

So, this could be fixed in bosh-deployment-resource by either.  Allowing bosh to upload the stemcell everytime allowing it to detect if the stemcell is there or not or enhancing the stemcell detection to determine if the stemcell is in every cpi uploading it if it is not.

I hope that helps clarify the issue.  Sorry for not being more clear before.  Thanks!

**Comment by drich10** [comment]
Thanks for the detailed explanation 👍 . In your manual fix did you run `upload-stemcell` without any additional flags? Currently the resource will _essentially_ attempt a `bosh upload-stemcell` for each stemcell in the `stemcells` array, so it would be interesting if a vanilla `upload-stemcell` command works where the resource failed. I'll definitely look into this!

P.S. no apology needed :)

**Comment by youngm** [comment]
@drich10 Hmm.....looking at the error we saw it looked as though bosh-deployment-resource detected that the stemcell was already uploaded (which it was to one cpi) prompting it to skip uploading it again.  However, perusing through the code I don't see any place where bosh-deployment-resource might have any of that logic.  Let me try to duplicate what I thought the issue was again and I'll do a little more investigation and report back.

**Comment by youngm** [comment]
Closing for now till I have time to try and dupe.
