### ISSUE TITLE
Implicit `get` following a `put` fails when using `put.params.source_file`

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-deployment-resource#5]
While the README documents that `source_file` only works on a `put`, every `put` in Concourse is followed by an implicit `get`. When using `source_file` only (no `source.target` in resource definition), the `put` succeeds but the implicit `get` fails with `Expected non-empty Director URL`:

![screen shot 2017-03-24 at 8 45 52 am](https://cloud.githubusercontent.com/assets/1923644/24302005/5aa5ac14-106e-11e7-9df9-3247dd2eced3.png)

**Comment by ljfranklin** [comment]
cc @drich10

**Comment by wendorf** [comment]
Thank you for the report! We've just cut [v2.2.0](https://github.com/cloudfoundry/bosh-deployment-resource/releases/tag/v2.2.0).
