### ISSUE TITLE
Expected non-empty Director URL

### ISSUE THREAD

**Issue by henderjm** [cloudfoundry/bosh-deployment-resource#53]
Hi,

After upgrading to concourse 4.0 we are seeing orange outputs from our jobs with the following error

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
Expected non-empty Director URL
```
We haven't noticed any side affects of this check failling in our pipelines yet.

Thanks,
Mark.

**Comment by drich10** [comment]
Hi Mark!

This happened as in one of the `Fixes` section of the [4.0 release notes](https://concourse-ci.org/download.html#v4.0.0). Specifically:
```
Previously, if a resource was only ever used as an explicit output of a job, it would always show up as black even if it was erroring. It will now show up as orange, like the other resources.
```
My expectation is any pipeline using the resource using only dynamic configuration will have this issue unless the resource has another flag added to the `source` section that turns the `check` operation into a no-op when using `source_file` on `out`.
