### ISSUE TITLE
source_file cannot be used with check

### ISSUE THREAD

**Issue by mattysweeps** [cloudfoundry/bosh-deployment-resource#57]
My checks always fail with 
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
Expected non-empty Director URL
```

Because I have not configured the resource source.
This is because I am using dynamic source, loaded from a bbl-state-resource.

What is the right thing to do? Is this the expected behavior of the check?

**Comment by drich10** [comment]
Unfortunately this is expected behavior, there is an option to `skip_check` available in the `source` section of configuration. 

Relevant issue: https://github.com/cloudfoundry/bosh-deployment-resource/issues/53
