### ISSUE TITLE
Deploy should fail if ops file path is invalid

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-deployment-resource#8]
We accidentally configured our pipeline with a path to an ops file that did not exist. Rather that the deploy failing with `invalid argument for flag `-o, --ops-file'` as the CLI does, the deploy succeed, ignoring the invalid file path. This surprised us, having the job fail would have let us track down the invalid path more quickly.

We're guessing it has something to do with how [globs are unfurled](https://github.com/cloudfoundry/bosh-deployment-resource/blob/master/tools/glob_unfurler.go) but we didn't dig too much.

**Comment by ljfranklin** [comment]
+10 CF points for sheer speed!

**Comment by wendorf** [comment]
This is now available in v2.5.0
