### ISSUE TITLE
Resource expects "stemcells" node in manifest where not necessarily applicable

### ISSUE THREAD

**Issue by reneighbor** [cloudfoundry/bosh-deployment-resource#9]
The CloudOps team attempted to switch to using this resource. We are currently not using Cloud Config for this deployment. Our deployment is erroring out due to the missing "stemcells" node in our manifest file (which is not necessary for Bosh1-style manifests).

The error being thrown is: "No stemcells section in deployment manifest" [thrown from here](https://github.com/cloudfoundry/bosh-deployment-resource/blob/9c70a78277a6681e728b12de265fe9400382eb0a/bosh/deployment_manifest.go#L43-L46)

We will switch back to the Ruby CLI - based resource for the time being. 

cc @pronoiac

**Comment by shreddedbacon** [comment]
When resource_pools is defined in cloud-config, there is no need to specify a stemcells section in the deployment manifest.

When I deploy something that uses a resource_pool, bosh-deployment-resource complains that stemcells is missing from my manifest, when it is not required.

**Comment by poblin-orange** [comment]
Hi, this bug is really annoying.

Just tried to workaround adding a v2 stemcells tag on my bosh v1 manifest
```
+ stemcells:
+ - alias: trusty
+   os: ubuntu-trusty
+   version: '3363.24'
Task 358165

19:25:26 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
19:25:27 | Preparing deployment: Preparing deployment (00:00:00)
            L Error: Deployment manifest contains 'stemcells' section, but it can only be used in cloud-config.

19:25:27 | Error: Deployment manifest contains 'stemcells' section, but it can only be used in cloud-config.

Started  Tue Jul 11 19:25:26 UTC 2017
Finished Tue Jul 11 19:25:27 UTC 2017
Duration 00:00:01

Task 358165 error
Could not deploy: Updating deployment: Expected task '358165' to succeed but was state is 'error
```

Bottom line: this concourse resource is uncompatible with bosh v1 syntax manifest (still the case for cloudfoundry)

 Any hint or expected corrections ?

**Comment by drich10** [comment]
Hi all, sorry for being late to the conversation. We originally designed this resource with v2 manifests in mind. I'm happy to look into what it would mean to fix this particular issue with the `stemcells` key. I'll post back to the issue after some investigation.

**Comment by drich10** [comment]
It seems like the resource itself should only be complaining about the omission of the `stemcells` key in the manifest if you attempt to use the `stemcells` upload/use in manifest feature described in the resource. There is currently no intent to make this feature work for v1 style manifests. Omitting the `stemcells` key from the `params` section of a `put` should get you past the error. If this is not the case could someone post the error they are getting from the resource?

**Comment by drich10** [comment]
I'm going to close this issue because I have only seen/received this issue in the case of a v1 style manifest with the `stemcells` option specified. The resource does _work_ with v1 manifests but there is currently no intent to make all optional features work with v1 styled manifests.
